# Generated by Django 4.2.11 on 2025-01-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(verbose_name='入职时间'),
        ),
    ]
