# Generated by Django 4.2.11 on 2025-01-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_alter_userinfo_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=32, verbose_name='手机号')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('level', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.SmallIntegerField(verbose_name='年龄'),
        ),
    ]
