# Generated by Django 4.2.11 on 2025-01-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0005_prettynum_alter_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已占用'), (1, '未占用')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '3级'), (2, '2级'), (1, '1级'), (4, '4级')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
